#!/usr/bin/env python3
# BoltBeam's size budget and duplicate-authority check. Modelled on tinygrad-arkey's sz.py: a token-based line
# counter with a hard cap. A line counts when it holds a code token: blank lines, comments and docstrings do not.
# Python is tokenized; Go has its // and /* */ comments stripped. Tests (tests/, *_test.go) are never counted.
# A file whose first lines carry an `@generated` / `autogenerated` marker is derived: reported, never budgeted.
#
# BUDGET_DIRS count against MAX_LINE_COUNT. INFO_DIRS are reported only.
# CAP: 47,000. On 2026-10-10 this counter read 44,726 budgeted lines (boltbeam/ 39,494 + tui/ 5,232; a plain
# non-blank non-comment count reads boltbeam/ as 42,884 because it keeps docstrings). 47,000 is 44,726 plus 5%
# (46,962), rounded up. Raising the cap is a decision, not a fix: the code has to earn
# the lines, and the change shows this table in its commit message. Duplicated knowledge does not earn lines.
#
# The second half is the duplicate-authority check (docs/coding-principles.md, "Centralize"). AUTHORITIES names each
# load-bearing table or constant and the one module that owns it. A detector per authority looks for a second
# DEFINITION elsewhere: an assignment, a dict/tuple/list/set literal, or a numeric keyword default. A mention in a
# comment, a docstring or a doc never fires. ALLOWED lists the duplicates that existed when the check landed; review
# landing 6 removes them. Any other hit fails the check with its file and line.
#
#   python3 sz.py            table, total, cap, then the authority check; exit 1 on either failure
#   SZ_FILES=1 python3 sz.py also list every file
import ast, itertools, json, os, re, sys, token, tokenize

BUDGET_DIRS = ["boltbeam", "tui"]
INFO_DIRS = ["tools"]
SCAN_DIRS = ["boltbeam", "tools"]  # where a second definition is looked for (tui is Go and reads the JSON records)
DEFAULT_MAX_LINE_COUNT = 47000
GEN_MARK = re.compile(r'@generated|autogenerated', re.I)
TOKEN_WHITELIST = [token.OP, token.NAME, token.NUMBER, token.STRING]

def is_docstring(t): return t.type == token.STRING and t.string.startswith(('"""', "'''")) and t.line.strip().startswith(('"""', "'''"))

def is_generated(path):
  try:
    with open(path, errors="ignore") as f: return bool(GEN_MARK.search("".join(itertools.islice(f, 6))))
  except OSError: return False

def is_test(rel): return rel.startswith("tests/") or "/tests/" in rel or rel.endswith("_test.go") or os.path.basename(rel).startswith("test_")

def go_lines(path):
  src = open(path, errors="ignore").read()
  src = re.sub(r'/\*.*?\*/', lambda m: "\n" * m.group(0).count("\n"), src, flags=re.S)
  out = 0
  for line in src.splitlines():
    # drop a // comment that is not inside a string or a rune
    code, q = [], None
    for i, c in enumerate(line):
      if q: q = None if c == q and line[i-1] != "\\" else q
      elif c in "\"'`": q = c
      elif line.startswith("//", i): break
      code.append(c)
    out += bool("".join(code).strip())
  return out

def py_lines(path):
  with tokenize.open(path) as f:
    toks = [t for t in tokenize.generate_tokens(f.readline) if t.type in TOKEN_WHITELIST and not is_docstring(t)]
  return len({x for t in toks for x in range(t.start[0], t.end[0] + 1)})

def gen_stats(base="."):
  table = []  # [relpath, lines, kind]
  for top in BUDGET_DIRS + INFO_DIRS:
    for path, dirs, files in os.walk(os.path.join(base, top)):
      dirs[:] = [d for d in dirs if d not in ("__pycache__", "testdata", "tests")]
      for name in files:
        if not name.endswith((".py", ".go")): continue
        fp = os.path.join(path, name); rel = os.path.relpath(fp, base).replace("\\", "/")
        if is_test(rel): continue
        try: n = py_lines(fp) if name.endswith(".py") else go_lines(fp)
        except (tokenize.TokenError, SyntaxError, UnicodeDecodeError, ValueError, OSError) as e:
          print(f"WARNING: failed to tokenize {rel}: {e}", file=sys.stderr); continue
        if n <= 0: continue
        table.append([rel, n, "generated" if is_generated(fp) else ("budgeted" if top in BUDGET_DIRS else "info")])
  return table

# --- the duplicate-authority check -------------------------------------------------------------------------------
# id -> (owner module, what it is). The owner's own definitions never fire.
AUTHORITIES = {
  "ggml_types":  ("boltbeam/profile/gguf.py", "the ggml type id <-> name table (GGML_TYPE_NAMES)"),
  "block_layout": ("boltbeam/profile/decode_roles.py", "bytes and elements per block (GGML_BLOCK_LAYOUTS)"),
  "roles":       ("boltbeam/vocab.py", "the role vocabulary (RoleClass, RoleGroup, WEIGHT_GEMV_ROLES)"),
  "chip_peaks":  ("boltbeam/target/targets.py", "measured chip peaks (data/targets.json, read by targets.py)"),
  "noisy_floor": ("boltbeam/collectors/kernel_timer.py", "the dispatch floor and the noisy constants"),
  "tolerance":   ("boltbeam/collectors/metal_native.py", "the correctness tolerance (TOLERANCE)"),
}
# (authority, file, symbol) -> review finding. Today's duplicates, recorded, not fixed. To remove in landing 6.
ALLOWED = {
  ("ggml_types", "boltbeam/profile/decode_roles.py", "GGML_TYPE_NAMES"): "C3, to remove in landing 6",
  ("ggml_types", "boltbeam/collectors/metal_native.py", "GGML_TYPES"): "C3, to remove in landing 6",
  ("ggml_types", "boltbeam/artifacts/llama_rocprof.py", "_GGML_QUANTS"): "C3, to remove in landing 6",
  ("block_layout", "boltbeam/collectors/metal_native.py", "BLOCK_BYTES"): "C3, to remove in landing 6",
  ("block_layout", "boltbeam/collectors/metal_native.py", "BLOCK_ELEMS"): "C3, to remove in landing 6",
  ("noisy_floor", "boltbeam/workflow/tie_out.py", "NOISY_RULE"): "C10, to remove in landing 6",
  ("tolerance", "boltbeam/search/role_compare.py", "TOLERANCE"): "C12, to remove in landing 6",
  ("tolerance", "boltbeam/search/primitive_plan.py", "seed"): "C12 (dev only), to remove in landing 6",
}

# canonical facts the detectors match against: a literal must AGREE with ggml to count as a copy of the table
LAYOUT = {"Q4_0": (32, 18), "Q5_0": (32, 22), "Q8_0": (32, 34), "Q4_K": (256, 144), "Q5_K": (256, 176), "Q6_K": (256, 210)}
TYPE_IDS = {"F32": 0, "F16": 1, "Q4_0": 2, "Q4_1": 3, "Q5_0": 6, "Q5_1": 7, "Q8_0": 8, "Q4_K": 12, "Q5_K": 13, "Q6_K": 14,
            "IQ3_XXS": 18, "IQ3_S": 21, "IQ2_S": 22, "IQ4_XS": 23, "BF16": 30}
TOL_NAME = re.compile(r'^_?(TOLERANCE|ATOL|RTOL|REL_TOL|ABS_TOL)$|_(ATOL|RTOL)$')
TOL_KEY = {"atol", "rtol", "rel_tol", "abs_tol", "tolerance"}
FLOOR_NAME = re.compile(r'NOISY|DISPATCH_FLOOR|FLOOR_(MULTIPLE|SHARE|US)')
FLOOR_KEY = re.compile(r'^(floor_share|floor_multiple|dispatch_floor(_us)?|noisy_[a-z_]*)$')
PEAK_NAME = re.compile(r'PEAK.*(GBS|TFLOPS|FLOPS|BW)|BANDWIDTH_GBS', re.I)
PEAK_KEY = re.compile(r'^(memory_bandwidth_gbs|peak_[a-z_]*(gbs|tflops|flops))$')

def _const(n): return n.value if isinstance(n, ast.Constant) else None
def _num(n):
  if isinstance(n, ast.Constant) and isinstance(n.value, (int, float)) and not isinstance(n.value, bool): return n.value
  if isinstance(n, ast.BinOp) and _num(n.left) is not None and _num(n.right) is not None: return 0.0  # 1 / 3
  return None

def _pairs(lit):
  """(key, value) pairs of a literal: dict items, and 2- or 3-tuples inside a sequence."""
  if isinstance(lit, ast.Dict): return [(k, v) for k, v in zip(lit.keys, lit.values) if k is not None]
  if isinstance(lit, (ast.List, ast.Tuple, ast.Set)):
    return [(e.elts[0], e.elts[1:]) for e in lit.elts if isinstance(e, ast.Tuple) and len(e.elts) >= 2]
  return []

def ggml_type_hits(lit):
  hits = set()
  for k, v in _pairs(lit):
    vs = v if isinstance(v, list) else [v]
    for a, b in [(_const(k), _const(x)) for x in vs]:
      if isinstance(a, int) and isinstance(b, str) and TYPE_IDS.get(b) == a: hits.add(("id", b))
      if isinstance(a, str) and isinstance(b, int) and not isinstance(b, bool) and TYPE_IDS.get(a) == b: hits.add(("name", a))
  # id -> name: two agreeing pairs. name -> id: three, since small ints (2, 6) are common values of other tables
  return sum(k == "id" for k, _ in hits) >= 2 or sum(k == "name" for k, _ in hits) >= 3

def layout_hits(lit):
  """A table that pairs quants (by name or ggml id) with their block bytes or a (elems, bytes) pair."""
  byid = {TYPE_IDS[q]: q for q in LAYOUT}
  hits = set()
  for k, v in _pairs(lit):
    q = _const(k); q = byid.get(q, q) if isinstance(q, int) and not isinstance(q, bool) else q
    if q not in LAYOUT: continue
    vals = [_const(x) for x in (v if isinstance(v, list) else (v.elts if isinstance(v, ast.Tuple) else [v]))]
    elems, nbytes = LAYOUT[q]
    if nbytes in vals or vals == [elems]: hits.add(q)
  return len(hits) >= 2

def role_values(base):
  tree = ast.parse(open(os.path.join(base, AUTHORITIES["roles"][0])).read())
  return {_const(s.value) for c in ast.walk(tree) if isinstance(c, ast.ClassDef) and c.name in ("RoleClass", "RoleGroup")
          for s in c.body if isinstance(s, ast.Assign) and isinstance(_const(s.value), str)} - {"other", "norm"}

def role_hits(lit, roles):
  if not isinstance(lit, (ast.List, ast.Tuple, ast.Set)): return False
  # a list that names most of a model's matrices is a second vocabulary; a policy's four-role subset is not
  return sum(_const(e) in roles for e in lit.elts) >= 8

def peak_values(base):
  rows = json.load(open(os.path.join(base, "boltbeam/data/targets.json")))["targets"]
  return {float(r["memory_bandwidth_gbs"]) for r in rows if isinstance(r.get("memory_bandwidth_gbs"), (int, float))}

def _names(t):
  if isinstance(t, ast.Name): return [t.id]
  if isinstance(t, ast.Attribute): return [t.attr]
  if isinstance(t, (ast.Tuple, ast.List)): return [n for e in t.elts for n in _names(e)]
  return []

def scan_file(rel, src, roles, peaks):
  """[(authority, symbol, line)] for every definition in this file that a detector matches."""
  out = []
  try: tree = ast.parse(src)
  except SyntaxError: return out
  for node in ast.walk(tree):
    targets, value = None, None
    if isinstance(node, ast.Assign): targets, value = node.targets, node.value
    elif isinstance(node, ast.AnnAssign) and node.value is not None: targets, value = [node.target], node.value
    if value is not None:
      names = [n for t in targets for n in _names(t)]
      sym = names[0] if names else "?"
      # tuple unpacking: NAME_A, NAME_B = 3.0, 60 pairs each name with its value
      pairs = list(zip(names, value.elts)) if isinstance(value, ast.Tuple) and len(names) == len(value.elts) > 1 else [(sym, value)]
      for name, val in pairs:
        lits = [n for n in ast.walk(val) if isinstance(n, (ast.Dict, ast.List, ast.Tuple, ast.Set))]
        if any(ggml_type_hits(l) for l in lits): out.append(("ggml_types", name, node.lineno))
        if any(layout_hits(l) for l in lits): out.append(("block_layout", name, node.lineno))
        if any(role_hits(l, roles) for l in lits): out.append(("roles", name, node.lineno))
        if TOL_NAME.search(name) and (_num(val) is not None or isinstance(val, ast.Dict)): out.append(("tolerance", name, node.lineno))
        if FLOOR_NAME.search(name) and (_num(val) is not None or isinstance(val, ast.Dict)): out.append(("noisy_floor", name, node.lineno))
        if PEAK_NAME.search(name) and _num(val) is not None: out.append(("chip_peaks", name, node.lineno))
        for d in (l for l in lits if isinstance(l, ast.Dict)):
          for k, v in zip(d.keys, d.values):
            key = _const(k) if k is not None else None
            if not isinstance(key, str) or _num(v) is None: continue
            if key in TOL_KEY and _num(v) != 0: out.append(("tolerance", name, node.lineno))
            if FLOOR_KEY.match(key): out.append(("noisy_floor", name, node.lineno))
            if PEAK_KEY.match(key) and _num(v) in peaks: out.append(("chip_peaks", name, node.lineno))
    if isinstance(node, ast.keyword) and node.arg in TOL_KEY and _num(node.value) not in (None, 0):
      out.append(("tolerance", node.arg, node.value.lineno))
  return sorted(set(out), key=lambda x: x[2])

def check_authorities(base="."):
  """(new hits, allowlisted hits found, stale allowlist entries)."""
  roles, peaks = role_values(base), peak_values(base)
  new, seen = [], {}
  for top in SCAN_DIRS:
    for path, dirs, files in os.walk(os.path.join(base, top)):
      dirs[:] = [d for d in dirs if d not in ("__pycache__", "tests")]
      for name in sorted(files):
        if not name.endswith(".py"): continue
        rel = os.path.relpath(os.path.join(path, name), base).replace("\\", "/")
        if is_test(rel): continue
        for auth, sym, line in scan_file(rel, open(os.path.join(path, name), errors="ignore").read(), roles, peaks):
          if rel == AUTHORITIES[auth][0]: continue
          key = (auth, rel, sym)
          if key in ALLOWED: seen[key] = line
          else: new.append((auth, rel, sym, line))
  return new, seen, [k for k in ALLOWED if k not in seen]

def main(base="."):
  table = gen_stats(base)
  if os.getenv("SZ_FILES", "0") == "1":
    for rel, n, kind in sorted(table, key=lambda x: -x[1]): print(f"{rel:80s} {n:6d} {kind}")
    print()
  authored = [x for x in table if x[2] != "generated"]
  groups = sorted(("/".join(x[0].rsplit("/", 1)[0].split("/")[:2]), x[1]) for x in authored)
  for d, g in itertools.groupby(groups, key=lambda x: x[0]):
    g = list(g); print(f"{d:30s} : {sum(x[1] for x in g):6d} in {len(g):3d} files")
  print()
  budgeted = sum(x[1] for x in table if x[2] == "budgeted")
  for top in BUDGET_DIRS + INFO_DIRS:
    print(f"{top:>10s} : {sum(x[1] for x in table if x[0].startswith(top + '/') and x[2] != 'generated'):6d}"
          f"{'' if top in BUDGET_DIRS else '   (reported, unbudgeted)'}")
  print(f" generated : {sum(x[1] for x in table if x[2] == 'generated'):6d}   (derived, unbudgeted)")
  cap = int(os.getenv("MAX_LINE_COUNT", str(DEFAULT_MAX_LINE_COUNT)))
  print(f"BUDGETED lines: {budgeted} / {cap}")
  ok = True
  if cap != -1 and budgeted > cap:
    print(f"OVER BUDGET: {budgeted} > {cap} lines. Remove lines, or raise the cap as a decision with this table.")
    ok = False
  new, seen, stale = check_authorities(base)
  print(f"\nauthorities: {len(AUTHORITIES)} registered, {len(seen)} known duplicates allowlisted (landing 6)")
  for (auth, rel, sym), line in sorted(seen.items()): print(f"  allowed  {rel}:{line} {sym} [{auth}] {ALLOWED[(auth, rel, sym)]}")
  # not fatal: an entry can name a file only the outer branches hold (dev, exp)
  for k in stale: print(f"  not on this branch, or already removed (drop it from ALLOWED once gone everywhere): {k}")
  for auth, rel, sym, line in new:
    print(f"DUPLICATE AUTHORITY: {rel}:{line} {sym} defines {AUTHORITIES[auth][1]}; the owner is {AUTHORITIES[auth][0]}")
  if new: ok = False
  return 0 if ok else 1

if __name__ == "__main__":
  sys.exit(main(sys.argv[1] if len(sys.argv) == 2 else "."))
